### ISSUE TITLE
Azimuth links mistakenly point to ncspot-snap

### ISSUE THREAD

**Issue by joelpurra** [popey/azimuth-snap#1]
Links on Snapcraft and (consequently) the Ubuntu (Snap) Store links/refers to `ncspot-snap` as both the project website and snap build configuration. Should be two different `azimuth`-related links.

- https://snapcraft.io/azimuth
- https://github.com/popey/ncspot-snap

Not too familiar with publishing to Snapcraft myself. Perhaps an automation issue?

**Comment by popey** [comment]
Thanks for filing this issue. Apologies I got to it so late. I guess this was a copy/paste error at *some* point!
Should be fixed now. Thanks again!

**Comment by joelpurra** [comment]
Thank you! FYI the sidebar link to the snap's website hasn't updated, but might be a caching issue.
